Class {
	#name : #GtAlgorithmerBlockVisitor,
	#superclass : #Object,
	#category : #'GToolkit-Algorithmer-Visitor'
}

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitAlgorithmer: anAlgorithmer [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitAssignVariableBlock: anAssignVariableBlock [
]

{ #category : #'visiting - types' }
GtAlgorithmerBlockVisitor >> visitBooleanType: aBooleanType [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitDefineVariableBlock: aDefineVariableBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitIfBlock: anIfBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitMessageSendBlock: aMessageSendBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitOperatorBlock: anOperatorBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitPrintlnBlock: aPrintlnBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitPushHeapBlock: aPushHeapBlock [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitSequenceBlock: aSequenceBlock [
]

{ #category : #'visiting - composition' }
GtAlgorithmerBlockVisitor >> visitStructure: anAlgorithmerStructure [
]

{ #category : #'visiting - composition' }
GtAlgorithmerBlockVisitor >> visitStructureField: anAlgorithmerStructureField [
]

{ #category : #'visiting - composition' }
GtAlgorithmerBlockVisitor >> visitTrait: anAlgorithmerTrait [
]

{ #category : #'visiting - composition' }
GtAlgorithmerBlockVisitor >> visitTraitMethod: anAlgorithmerMethod [
]

{ #category : #'visiting - types' }
GtAlgorithmerBlockVisitor >> visitTraitType: aTraitType [
]

{ #category : #'visiting - types' }
GtAlgorithmerBlockVisitor >> visitUnknownType: anUnknownType [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitVariableBlock: aVariableBlock [
]

{ #category : #'visiting - types' }
GtAlgorithmerBlockVisitor >> visitVoidType: aVoidType [
]

{ #category : #visiting }
GtAlgorithmerBlockVisitor >> visitWhileBlock: aWhileBlock [
]
