Trait {
	#name : #TGtAlgorithmerBlockVisitor,
	#category : #'GToolkit-Algorithmer-Visitor'
}

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitAssignStructureFieldBlock: anAssignStructureFieldBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitAssignVariableBlock: anAssignVariableBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitDefineVariableBlock: aDefineVariableBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitIfBlock: anIfBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitMessageSendBlock: aMessageSendBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitOperatorBlock: anOperatorBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitPrintlnBlock: aPrintlnBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitPushHeapBlock: aPushHeapBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitReadMethodArgumentBlock: aReadMethodArgumentBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitReadStructureFieldBlock: aReadStructureField [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitReadVariableBlock: aVariableBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitSequenceBlock: aSequenceBlock [
]

{ #category : #'visiting - blocks' }
TGtAlgorithmerBlockVisitor >> visitWhileBlock: aWhileBlock [
]
