Trait {
	#name : #TGtAlgorithmerCompositionVisitor,
	#category : #'GToolkit-Algorithmer-Visitor'
}

{ #category : #'visiting - composition' }
TGtAlgorithmerCompositionVisitor >> visitAlgorithmer: anAlgorithmer [
]

{ #category : #'visiting - composition' }
TGtAlgorithmerCompositionVisitor >> visitStructure: anAlgorithmerStructure [
]

{ #category : #'visiting - composition' }
TGtAlgorithmerCompositionVisitor >> visitStructureField: anAlgorithmerStructureField [
]

{ #category : #'visiting - composition' }
TGtAlgorithmerCompositionVisitor >> visitTrait: anAlgorithmerTrait [
]

{ #category : #'visiting - composition' }
TGtAlgorithmerCompositionVisitor >> visitTraitMethod: anAlgorithmerMethod [
]
