Trait {
	#name : #TGtAlgorithmerTypeVisitor,
	#category : #'GToolkit-Algorithmer-Visitor'
}

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitBooleanType: aBooleanType [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitClassType: aClassType [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitFloat32Type: aFloat32Type [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitInt32Type: anInt32Type [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitTraitType: aTraitType [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitUnknownType: anUnknownType [
]

{ #category : #'visiting - types' }
TGtAlgorithmerTypeVisitor >> visitVoidType: aVoidType [
]
